### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by dlo** [lionheart/git-bigstore#40]

**Comment by MQQ** [comment]
Hi there, just want to check if there is any plan or effort for this. If not, I can try to help. Thanks!

**Comment by dlo** [comment]
Hey @MQQ! So far, I haven't had the time, but if you're willing to, I'd be super happy to accept any PRs. :) Thank you!

**Comment by MQQ** [comment]
@dlo Here is a quick PR for 2/3 compatible. #43 

Notes: 
1) The biggest problem is that `python-cloudfiles` is a very outdated package, and I can't find a straightforward replacement after quickly searching around. I myself also never used the rackspace cloud so I have no idea. I currently put a python2 marker in the setup.py so that `python-cloudfiles` will only be installed in python2, which means the rackspace backend will fail under python3. 

2) I have to relax the version requirement for gitpython, since the old gitpython was also not compatible to python2. It seems the most recent gitpython==2.1.11 works fine. 

Please let me know what you think. Thanks!

**Comment by MQQ** [comment]
@dlo Sorry for pushing this. But it would be great if this can be resolved earlier, which will really help my current project workflow. Thanks!

**Comment by dlo** [comment]
Hi @MQQ! Thanks again for contributing! I just had a few comments on the PR for you to take a look at. Otherwise everything looks great.

**Comment by MQQ** [comment]
ah, I added a review comment a couple of days ago but I forgot to actually click the submit button. My bad :p

**Comment by MQQ** [comment]
Great! Very happy to help!
